spring:
  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: weekly-sentiment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    properties:
      session.timeout.ms: 45000

      spring.json.trusted.packages: "net.engineeringdigest.journalApp.model"

      security.protocol: SASL_SSL

      sasl.mechanism: PLAIN

      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="CLQJ77VNMVYIU3PG"
        password="cfltyN9FAm7T+29hL9HWNY54VMvAMmPTCmqb6GhAg1iYQLe/27XZqLLHS5yRFjGg";

  redis:
    uri: redis://default:XlTc4gMX90LMIEOj32w0aUdOrIbXvHIa@amicable-chicken-bluebell-77802.db.redis.io:19871

  data:
    mongodb:
      uri: mongodb+srv://panditnihar919_db_user:XhkXLLMARpyNa1J9@cluster0.o8ylzga.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: panditnihar919@gmail.com
    password: aqte snmd jdxs xeck
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /journal

weather:
  api:
    key: D2W9JUPTR8XNWD4BTAECUZ889



